name = "logger"
#account_id = ""
#route = ""
workers_dev = true
compatibility_date = "2022-08-08"
main = "src/index.ts"

kv_namespaces = [ 
  { binding = "Logger", id = "953bc25038ae43b3836c5d45a97f8b36" }
]

[build]
command = "npm install && npm run build"
