name = "logger"
workers_dev = true
compatibility_date = "2022-08-08"
main = "src/index.ts"

kv_namespaces = [ 
  { binding = "Logger", id = "f56e70cbf0b04a839eb209f4cde339e7" }
]

[build]
command = "npm install && npm run build"
